source 'https://cdn.cocoapods.org/'
platform :ios, '9.0'

target 'CheetahDemo' do
  pod 'Cheetah-iOS', podspec: 'https://raw.githubusercontent.com/Picovoice/cheetah/v1.1-ios/binding/ios/Cheetah-iOS.podspec'
  pod 'ios-voice-processor', '~> 1.0.2'
end
