source 'https://cdn.cocoapods.org/'
platform :ios, '13.0'

target 'CheetahDemo' do
  pod 'Cheetah-iOS', :podspec => 'https://raw.githubusercontent.com/Picovoice/cheetah/v2.0-ios/binding/ios/Cheetah-iOS.podspec'
  pod 'ios-voice-processor', '~> 1.1.0'
end
