name: Documentation
description: Issues around documentation of Cheetah
title: "Cheetah Documentation Issue: "
labels: ["documentation"]
body:
  - type: textarea
    id: url
    attributes:
      label: What is the URL of the doc?
    validations:
      required: true
  - type: textarea
    id: issue
    attributes:
      label: What's the nature of the issue?
      description: e.g. steps do not work, typos/grammar/spelling, out of date, etc.
    validations:
      required: true
