name: Feature request
description: Cheetah suggestion
title: "Cheetah Feature Request: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: Please provide a clear and concise description of what the problem is.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: Please provide a clear and concise description of what you would like to happen.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Please provide a clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Please provide any other context here.
    validations:
      required: false
