[package]
name = "pv_cheetah_micdemo"
version = "2.0.0"
edition = "2018"

[dependencies]
chrono = "0.4.20"
clap = "3.2.16"
ctrlc = "3.2.2"
hound = "3.4.0"
itertools = "0.10.3"
pv_cheetah = "=2.0.2"
pv_recorder = "=1.2.2"
