source 'https://cdn.cocoapods.org/'
platform :ios, '13.0'

target 'CheetahAppTest' do
  pod 'Cheetah-iOS', '~> 2.0.0'
end

target 'CheetahAppTestUITests' do
  pod 'Cheetah-iOS', '~> 2.0.0'
end

target 'PerformanceTest' do
  pod 'Cheetah-iOS', '~> 2.0.0'
end
