name: Run filedemo

inputs:
  access_key:
    required: true
  library_path:
    required: true
  model_path:
    required: true
  audio_path:
    required: true
  init_performance_threshold_sec:
    required: false
    type: number
  proc_performance_threshold_sec:
    required: false
    type: number

runs:
  using: "composite"
  steps:
  - run: >
      ./build/cheetah_demo_file
      -a ${{ inputs.access_key }}
      -l ${{ inputs.library_path }}
      -m ${{ inputs.model_path }}
      ${{ inputs.audio_path }}
    if: "${{ inputs.proc_performance_threshold_sec == '' || inputs.init_performance_threshold_sec == '' }}"
    working-directory: demo/c
    shell: bash

  - run: >
      ./build/cheetah_demo_file
      -a ${{ inputs.access_key }}
      -l ${{ inputs.library_path }}
      -m ${{ inputs.model_path }}
      -i ${{ inputs.init_performance_threshold_sec }}
      -p ${{ inputs.proc_performance_threshold_sec }}
      ${{ inputs.audio_path }}
    if: "${{ inputs.proc_performance_threshold_sec != '' && inputs.init_performance_threshold_sec != '' }}"
    working-directory: demo/c
    shell: bash
  