name: Android AppCenter Tests

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'demo/android/CheetahDemo/**'
      - '!demo/android/CheetahDemo/README.md'
      - '.github/workflows/android-appcenter.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'demo/android/CheetahDemo/**'
      - '!demo/android/CheetahDemo/README.md'
      - '.github/workflows/android-appcenter.yml'

defaults:
  run:
    working-directory: demo/android/CheetahDemo

jobs:
  build:
    name: Run Android Tests on AppCenter
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.0

    - name: Install AppCenter CLI
      run: npm install -g appcenter-cli

    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Binding pre-build
      run: ./gradlew assemble
      working-directory: binding/android

    - name: Copy test_resources
      run: ./copy_test_resources.sh

    - name: Inject AccessKey
      run: echo pvTestingAccessKey="${{secrets.PV_VALID_ACCESS_KEY}}" >> local.properties

    - name: Inject Init Performance Threshold
      run: echo initPerformanceThresholdSec="7.5" >> local.properties

    - name: Inject Process Performance Threshold
      run: echo procPerformanceThresholdSec="2.5" >> local.properties

    - name: Build app
      run: ./gradlew assembleDebug

    - name: Build androidTest
      run: ./gradlew assembleAndroidTest

    - name: Run tests on AppCenter
      run: appcenter test run espresso
        --token ${{secrets.APPCENTERAPITOKEN}}
        --app "Picovoice/Cheetah-Android"
        --devices "Picovoice/android-min-max"
        --app-path cheetah-demo-app/build/outputs/apk/debug/cheetah-demo-app-debug.apk
        --test-series "cheetah-android"
        --locale "en_US"
        --build-dir cheetah-demo-app/build/outputs/apk/androidTest/debug
