name: Android Performance

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'lib/android/**'
      - 'lib/common/**'
      - '.github/workflows/android-perf.yml'
  pull_request:
    branches: [ master, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'lib/android/**'
      - 'lib/common/**'
      - '.github/workflows/android-perf.yml'

defaults:
  run:
    working-directory: binding/android/CheetahTestApp

jobs:
  build:
    name: Run Android Speed Tests on BrowserStack
    runs-on: ubuntu-latest

    strategy:
      matrix:
        device: [ android-perf ]
        include:
        - device: android-perf
          initPerformanceThresholdSec: 4.0
          procPerformanceThresholdSec: 2.3

    steps:
    - uses: actions/checkout@v3

    - name: Installing Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run:
        pip3 install requests

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

############## REMOVE AFTER RELEASE ##########################
    - name: Build binding
      run: ./gradlew assembleRelease --info
      working-directory: binding/android/Cheetah
############## REMOVE AFTER RELEASE ##########################

    - name: Copy test_resources
      run: ./copy_test_resources.sh

    - name: Inject AccessKey
      run: echo pvTestingAccessKey="${{secrets.PV_VALID_ACCESS_KEY}}" >> local.properties

    - name: Inject Number of Iterations
      run: echo numTestIterations="30" >> local.properties

    - name: Inject Android keystore variables
      run: |
        echo storePassword="${{secrets.ANDROID_RELEASE_KEYSTORE_PASSWORD}}" >> local.properties
        echo keyPassword="${{secrets.ANDROID_RELEASE_KEYSTORE_PASSWORD}}" >> local.properties
        echo keyAlias=picovoice >> local.properties
        echo storeFile=../picovoice.jks >> local.properties

    - name: Setup Android keystore file
      run: echo "${{secrets.ANDROID_RELEASE_KEYSTORE_FILE_B64}}" | base64 -d > picovoice.jks

    - name: Inject Init Performance Threshold
      run: echo initPerformanceThresholdSec="${{ matrix.initPerformanceThresholdSec }}" >> local.properties

    - name: Inject Proc Performance Threshold
      run: echo procPerformanceThresholdSec="${{ matrix.procPerformanceThresholdSec }}" >> local.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build app
      run: ./gradlew assembleDebug

    - name: Build androidTest
      run: ./gradlew assembleAndroidTest -DtestBuildType=perf

    - name: Run tests on BrowserStack
      run: python3 ../../../script/automation/browserstack.py
        --type espresso
        --username "${{secrets.BROWSERSTACK_USERNAME}}"
        --access_key "${{secrets.BROWSERSTACK_ACCESS_KEY}}"
        --project_name "Cheetah-Android-Performance"
        --devices "${{ matrix.device }}"
        --app_path "cheetah-test-app/build/outputs/apk/en/debug/cheetah-test-app-en-debug.apk"
        --test_path "cheetah-test-app/build/outputs/apk/androidTest/en/debug/cheetah-test-app-en-debug-androidTest.apk"

