name: Android BrowserStack Tests

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'binding/android/CheetahTestApp/**'
      - '.github/workflows/android-browserstack.yml'
  pull_request:
    branches: [ master, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'binding/android/CheetahTestApp/**'
      - '.github/workflows/android-browserstack.yml'

defaults:
  run:
    working-directory: binding/android/CheetahTestApp

jobs:
  build:
    name: Run Android Tests on BrowserStack
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Installing Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run:
        pip3 install requests

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Copy test_resources
      run: ./copy_test_resources.sh

    - name: Inject AccessKey
      run: echo pvTestingAccessKey="${{secrets.PV_VALID_ACCESS_KEY}}" >> local.properties

    - name: Inject Android keystore variables
      run: |
        echo storePassword="${{secrets.ANDROID_RELEASE_KEYSTORE_PASSWORD}}" >> local.properties
        echo keyPassword="${{secrets.ANDROID_RELEASE_KEYSTORE_PASSWORD}}" >> local.properties
        echo keyAlias=picovoice >> local.properties
        echo storeFile=../picovoice.jks >> local.properties

    - name: Setup Android keystore file
      run: echo "${{secrets.ANDROID_RELEASE_KEYSTORE_FILE_B64}}" | base64 -d > picovoice.jks

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build app
      run: ./gradlew assembleDebug

    - name: Build androidTest
      run: ./gradlew assembleAndroidTest

    - name: Run tests on BrowserStack
      run: python3 ../../../script/automation/browserstack.py
        --type espresso
        --username "${{secrets.BROWSERSTACK_USERNAME}}"
        --access_key "${{secrets.BROWSERSTACK_ACCESS_KEY}}"
        --project_name "Cheetah-Android"
        --devices "android-min-max"
        --app_path "cheetah-test-app/build/outputs/apk/debug/cheetah-test-app-debug.apk"
        --test_path "cheetah-test-app/build/outputs/apk/androidTest/debug/cheetah-test-app-debug-androidTest.apk"

  build-integ:
    name: Run Android Integration Tests on BrowserStack
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Installing Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run:
        pip3 install requests

    - name: Install AppCenter CLI
      run: npm install -g appcenter-cli

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Copy test_resources
      run: ./copy_test_resources.sh

    - name: Inject AccessKey
      run: echo pvTestingAccessKey="${{secrets.PV_VALID_ACCESS_KEY}}" >> local.properties

    - name: Inject Android keystore variables
      run: |
        echo storePassword="${{secrets.ANDROID_RELEASE_KEYSTORE_PASSWORD}}" >> local.properties
        echo keyPassword="${{secrets.ANDROID_RELEASE_KEYSTORE_PASSWORD}}" >> local.properties
        echo keyAlias=picovoice >> local.properties
        echo storeFile=../picovoice.jks >> local.properties

    - name: Setup Android keystore file
      run: echo "${{secrets.ANDROID_RELEASE_KEYSTORE_FILE_B64}}" | base64 -d > picovoice.jks

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build app
      run: ./gradlew assembleRelease

    - name: Build androidTest
      run: ./gradlew assembleReleaseAndroidTest -DtestBuildType=integ

    - name: Run tests on BrowserStack
      run: python3 ../../../script/automation/browserstack.py
        --type espresso
        --username "${{secrets.BROWSERSTACK_USERNAME}}"
        --access_key "${{secrets.BROWSERSTACK_ACCESS_KEY}}"
        --project_name "Cheetah-Android-Integration"
        --devices "android-min-max"
        --app_path "cheetah-test-app/build/outputs/apk/release/cheetah-test-app-release.apk"
        --test_path "cheetah-test-app/build/outputs/apk/androidTest/release/cheetah-test-app-release-androidTest.apk"

