name: iOS Performance

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'lib/ios/**'
      - 'lib/common/**'
      - '.github/workflows/ios-perf.yml'
  pull_request:
    branches: [ master, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'lib/ios/**'
      - 'lib/common/**'
      - '.github/workflows/ios-perf.yml'

defaults:
  run:
    working-directory: binding/ios/CheetahAppTest

jobs:
  build:
    name: Run iOS Tests on BrowserStack
    runs-on: macos-latest

    strategy:
      matrix:
        device: [ ios-perf ]
        include:
        - device: ios-perf
          initPerformanceThresholdSec: 2.5
          procPerformanceThresholdSec: 0.75

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Installing Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run:
          pip3 install requests

      - name: Make build dir
        run: mkdir ddp

      - name: Inject AccessKey
        run: sed -i '.bak' 's:{TESTING_ACCESS_KEY_HERE}:${{secrets.PV_VALID_ACCESS_KEY}}:'
          PerformanceTest/PerformanceTest.swift

      - name: Inject Number of Iterations
        run: sed -i '.bak' 's:{NUM_TEST_ITERATIONS}:30:'
          PerformanceTest/PerformanceTest.swift

      - name: Inject Performance Threshold
        run: sed -i '.bak'
          '1,/{INIT_PERFORMANCE_THRESHOLD_SEC}/s/{INIT_PERFORMANCE_THRESHOLD_SEC}/${{ matrix.initPerformanceThresholdSec }}/'
          PerformanceTest/PerformanceTest.swift

      - name: Inject Performance Threshold
        run: sed -i '.bak'
          '1,/{PROC_PERFORMANCE_THRESHOLD_SEC}/s/{PROC_PERFORMANCE_THRESHOLD_SEC}/${{ matrix.procPerformanceThresholdSec }}/'
          PerformanceTest/PerformanceTest.swift

      - name: XCode Build
        run: xcrun xcodebuild build-for-testing
          -configuration Debug
          -workspace CheetahAppTest.xcworkspace
          -sdk iphoneos
          -scheme PerformanceTest
          -derivedDataPath ddp
          CODE_SIGNING_ALLOWED=NO

      - name: Generating ipa
        run: cd ddp/Build/Products/Debug-iphoneos/ &&
          mkdir Payload &&
          cp -r CheetahAppTest.app Payload &&
          zip --symlinks -r CheetahAppTest.ipa Payload &&
          rm -r Payload

      - name: Zipping Tests
        run: cd ddp/Build/Products/Debug-iphoneos/ &&
          zip --symlinks -r PerformanceTest.zip PerformanceTest-Runner.app

      - name: Run tests on BrowserStack
        run: python3 ../../../script/automation/browserstack.py
          --type xcuitest
          --username "${{secrets.BROWSERSTACK_USERNAME}}"
          --access_key "${{secrets.BROWSERSTACK_ACCESS_KEY}}"
          --project_name "Cheetah-iOS-Performance"
          --devices "${{ matrix.device }}"
          --app_path "ddp/Build/Products/Debug-iphoneos/CheetahAppTest.ipa"
          --test_path "ddp/Build/Products/Debug-iphoneos/PerformanceTest.zip"
