name: Java

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'binding/java/**'
      - '!binding/java/README.md'
      - 'lib/commom/**'
      - 'lib/java/**'
      - '.github/workflows/java.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'binding/java/**'
      - '!binding/java/README.md'
      - 'lib/commom/**'
      - 'lib/java/**'
      - '.github/workflows/java.yml'

defaults:
  run:
    working-directory: binding/java

jobs:
  build-github-hosted:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build
      run: ./gradlew assemble

    - name: Test
      run: ./gradlew test -DpvTestingAccessKey="${{secrets.PV_VALID_ACCESS_KEY}}"

  build-self-hosted:
    runs-on: ${{ matrix.machine }}

    strategy:
      matrix:
        machine: [rpi3-32, rpi3-64, rpi4-32, rpi4-64, jetson]

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: ./gradlew assemble

    - name: Test
      run: ./gradlew test -DpvTestingAccessKey="${{secrets.PV_VALID_ACCESS_KEY}}"
