name: Java

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'binding/java/**'
      - '!binding/java/README.md'
      - 'lib/java/**'
      - 'resources/contexts/beaglebone/**'      
      - 'resources/contexts/jetson/**'
      - 'resources/contexts/linux/**'
      - 'resources/contexts/mac/**'
      - 'resources/contexts/raspberry-pi/**'
      - 'resources/contexts/windows/**'
      - '.github/workflows/java.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'binding/java/**'
      - '!binding/java/README.md'
      - 'lib/java/**'
      - 'resources/contexts/beaglebone/**'      
      - 'resources/contexts/jetson/**'
      - 'resources/contexts/linux/**'
      - 'resources/contexts/mac/**'
      - 'resources/contexts/raspberry-pi/**'
      - 'resources/contexts/windows/**'
      - '.github/workflows/java.yml'

defaults:
  run:
    working-directory: binding/java

jobs:
  build-github-hosted:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
        - os: ubuntu-latest
          init_performance_threshold_sec: 2.5
          proc_performance_threshold_sec: 0.9
        - os: windows-latest
          init_performance_threshold_sec: 3.0
          proc_performance_threshold_sec: 0.9
        - os: macos-latest
          init_performance_threshold_sec: 2.8
          proc_performance_threshold_sec: 0.9

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

    - name: Build
      run: ./gradlew assemble

    - name: Test
      run: |
        ./gradlew test -DpvTestingAccessKey="${{secrets.PV_VALID_ACCESS_KEY}}" \
          -DinitPerformanceThresholdSec="${{matrix.init_performance_threshold_sec}}" \ 
          -DprocPerformanceThresholdSec="${{matrix.proc_performance_threshold_sec}}"

  build-self-hosted:
    runs-on: ${{ matrix.machine }}

    strategy:
      matrix:
        machine: [rpi3-32, rpi3-64, rpi4-32, rpi4-64, jetson]
        include:
        - machine: rpi3-32
          init_performance_threshold_sec: 11.0
          proc_performance_threshold_sec: 3.4
        - machine: rpi3-64
          init_performance_threshold_sec: 16.0
          proc_performance_threshold_sec: 3.6
        - machine: rpi4-32
          init_performance_threshold_sec: 8.0
          proc_performance_threshold_sec: 2.3
        - machine: rpi4-64
          init_performance_threshold_sec: 8.0
          proc_performance_threshold_sec: 2.3
        - machine: jetson
          init_performance_threshold_sec: 8.0
          proc_performance_threshold_sec: 2.3

    steps:
    - uses: actions/checkout@v2

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

    - name: Build
      run: ./gradlew assemble

    - name: Test
      run: |
        ./gradlew test -DpvTestingAccessKey="${{secrets.PV_VALID_ACCESS_KEY}}" \
          -DinitPerformanceThresholdSec="${{matrix.init_performance_threshold_sec}}" \ 
          -DprocPerformanceThresholdSec="${{matrix.proc_performance_threshold_sec}}"
