name: Java Demos

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'demo/java/**'
      - '!demo/java/README.md'
      - '.github/workflows/java-demos.yml'
  pull_request:
    branches: [ master, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'demo/java/**'
      - '!demo/java/README.md'
      - '.github/workflows/java-demos.yml'

defaults:
  run:
    working-directory: demo/java

jobs:
  build-github-hosted:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java-version: ['11', '17', '19']

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'

    - name: Build
      run: ./gradlew build

    - name: Run filedemo
      run: java -jar build/libs/cheetah-file-demo.jar -a  ${{secrets.PV_VALID_ACCESS_KEY}} -i ../../resources/audio_samples/test.wav

  build-self-hosted:
    runs-on: ${{ matrix.machine }}

    strategy:
      matrix:
        machine: [rpi3-32, rpi3-64, rpi4-32, rpi4-64, rpi5-64, jetson]

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: ./gradlew build

    - name: Run filedemo
      run: java -jar build/libs/cheetah-file-demo.jar -a  ${{secrets.PV_VALID_ACCESS_KEY}} -i ../../resources/audio_samples/test.wav
