name: Java

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'binding/java/**'
      - '!binding/java/README.md'
      - 'lib/commom/**'
      - 'lib/java/**'
      - '.github/workflows/java.yml'
  pull_request:
    branches: [ master, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'binding/java/**'
      - '!binding/java/README.md'
      - 'lib/commom/**'
      - 'lib/java/**'
      - '.github/workflows/java.yml'

defaults:
  run:
    working-directory: binding/java

jobs:
  build-github-hosted:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java-version: ['11', '17', '19']

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'

    - name: Build
      run: ./gradlew assemble

    - name: Test
      run: ./gradlew test --info --tests CheetahTest -DpvTestingAccessKey="${{secrets.PV_VALID_ACCESS_KEY}}"

  build-self-hosted:
    runs-on: ${{ matrix.machine }}

    strategy:
      matrix:
        machine: [rpi3-32, rpi3-64, rpi4-32, rpi4-64, rpi5-64, jetson]

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: ./gradlew assemble

    - name: Test
      run: ./gradlew test --info --tests CheetahTest -DpvTestingAccessKey="${{secrets.PV_VALID_ACCESS_KEY}}"
