name: Node.js

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'binding/nodejs/**'
      - '!binding/nodejs/README.md'
      - 'lib/node/**'
      - '.github/workflows/nodejs.yml'

  pull_request:
    branches: [ master ]
    paths:
      - 'binding/nodejs/**'
      - '!binding/nodejs/README.md'
      - 'lib/node/**'
      - '.github/workflows/nodejs.yml'

defaults:
  run:
    working-directory: binding/nodejs

jobs:
  build-github-hosted:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [14.x, 16.x]
        include:
        - os: ubuntu-latest
          init_performance_threshold_sec: 3.0
          proc_performance_threshold_sec: 0.9
        - os: windows-latest
          init_performance_threshold_sec: 3.0
          proc_performance_threshold_sec: 0.9
        - os: macos-latest
          init_performance_threshold_sec: 3.0
          proc_performance_threshold_sec: 0.9

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Pre-build dependencies
      run: npm install yarn

    - name: Install dependencies
      run: yarn install

    - name: Test
      run: yarn test --access_key=${{secrets.PV_VALID_ACCESS_KEY}} --init_performance_threshold_sec=${{matrix.init_performance_threshold_sec}} --proc_performance_threshold_sec=${{matrix.proc_performance_threshold_sec}}

  build-self-hosted:
    runs-on: ${{ matrix.machine }}

    strategy:
      fail-fast: false
      matrix:
        machine: [rpi3-32, rpi3-64, rpi4-32, rpi4-64, jetson]
        include:
        - machine: rpi3-32
          init_performance_threshold_sec: 9.0
          proc_performance_threshold_sec: 3.4
        - machine: rpi3-64
          init_performance_threshold_sec: 15.0
          proc_performance_threshold_sec: 3.6
        - machine: rpi4-32
          init_performance_threshold_sec: 8.0
          proc_performance_threshold_sec: 2.2
        - machine: rpi4-64
          init_performance_threshold_sec: 8.0
          proc_performance_threshold_sec: 2.2
        - machine: jetson
          init_performance_threshold_sec: 8.0
          proc_performance_threshold_sec: 2.2

    steps:
    - uses: actions/checkout@v2

    - name: Pre-build dependencies
      run: npm install --global yarn

    - name: Install dependencies
      run: yarn install

    - name: Test
      run: |
        yarn test --access_key=${{secrets.PV_VALID_ACCESS_KEY}} \ 
          --init_performance_threshold_sec=${{matrix.init_performance_threshold_sec}} \
          --proc_performance_threshold_sec=${{matrix.proc_performance_threshold_sec}}


  build-self-hosted:
    runs-on: ${{ matrix.machine }}

    strategy:
      matrix:
        machine: [rpi3-32, rpi3-64, rpi4-32, rpi4-64, jetson]
        include:
        - machine: rpi3-32
          init_performance_threshold_sec: 9.0
          proc_performance_threshold_sec: 3.4
        - machine: rpi3-64
          init_performance_threshold_sec: 15.0
          proc_performance_threshold_sec: 3.6
        - machine: rpi4-32
          init_performance_threshold_sec: 8.0
          proc_performance_threshold_sec: 2.2
        - machine: rpi4-64
          init_performance_threshold_sec: 8.0
          proc_performance_threshold_sec: 2.2
        - machine: jetson
          init_performance_threshold_sec: 8.0
          proc_performance_threshold_sec: 2.2

    steps:
    - uses: actions/checkout@v2

    - name: Pre-build dependencies
      run: npm install --global yarn

    - name: Install dependencies
      run: yarn install

    - name: Test
      run: |
        yarn test --access_key=${{secrets.PV_VALID_ACCESS_KEY}} \ 
          --init_performance_threshold_sec=${{matrix.init_performance_threshold_sec}} \
          --proc_performance_threshold_sec=${{matrix.proc_performance_threshold_sec}}
