name: Python Demos

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - 'demo/python/**'
      - '!demo/python/README.md'
  pull_request:
    branches: [master]
    paths:
      - 'demo/python/**'
      - '!demo/python/README.md'

defaults:
  run:
    working-directory: demo/python

jobs:
  build-github-hosted:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Pre-build dependencies
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Test
      run: python cheetah_demo_file.py --access_key ${{secrets.PV_VALID_ACCESS_KEY}} --audio_paths ../../resources/audio_samples/test.wav

  build-self-hosted:
    runs-on: ${{ matrix.machine }}

    strategy:
      matrix:
        machine: [rpi3, rpi4, jetson]

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: pip3 install -r requirements.txt

    - name: Test
      run: python3 cheetah_demo_file.py --access_key ${{secrets.PV_VALID_ACCESS_KEY}} --audio_paths ../../resources/audio_samples/test.wav